from pydantic import BaseModel, Field
from typing import Optional

# Here we designed our whole schema for our webot that is chat system. (Both layer request and response).....

# ── Request Schemas (what frontend SENDS to API) ──────────────────────────────

class SendMessageRequest(BaseModel):
    """Frontend sends this when user types a message."""
    thread_id: str = Field(..., description="Unique conversation thread ID")
    message: str = Field(..., min_length=1, description="User's message")


class NewThreadRequest(BaseModel):
    """Frontend sends this when user clicks New Chat."""
    thread_id: str = Field(..., description="New unique thread ID generated by frontend")


class GenerateTitleRequest(BaseModel):
    """Frontend sends this to auto-generate a chat title."""
    first_message: str = Field(..., description="First message of the conversation")


# ── Response Schemas (what API SENDS back to frontend) ────────────────────────

class SendMessageResponse(BaseModel):
    """API returns this after processing a message."""
    thread_id: str
    response: str = Field(..., description="AI's response text")


class ChatMessage(BaseModel):
    """A single message in a conversation."""
    role: str = Field(..., description="Either 'user' or 'assistant'")
    content: str


class HistoryResponse(BaseModel):
    """API returns this when frontend loads a conversation."""
    thread_id: str
    messages: list[ChatMessage]


class NewThreadResponse(BaseModel):
    """API returns this after creating a new thread."""
    thread_id: str
    message: str = "New thread created successfully"


class GenerateTitleResponse(BaseModel):
    """API returns this with the generated title."""
    title: str


class ErrorResponse(BaseModel):
    """API returns this when something goes wrong."""
    detail: str